from pydantic import BaseModel
from typing import List


class IncidentRequest(BaseModel):
    """Input schema for incident processing requests."""
    
    incident: str


class IncidentClassification(BaseModel):
    """Structured output generated by the Triage Agent."""

    severity: str
    category: str
    entities: List[str]


class KnowledgeResponse(BaseModel):
    """Schema for retrieved knowledge base documents."""

    retrieved_docs: List[str]


class RemediationResponse(BaseModel):
    """Schema for remediation recommendations generated by the LLM."""

    steps: List[str]


class FinalResponse(BaseModel):
    """Final response returned to the user after workflow execution."""

    severity: str
    category: str
    remediation: List[str]
    summary: str